### ISSUE TITLE
Data18 scraper not working

### ISSUE THREAD

**Issue by rod8687** [DoctorD1501/JAVMovieScraper#149]
The Data18 scraper does not work anymore, it starts searching but almost stops again right away.
maybe data18 changed something about the website?

**Comment by DoctorD1501** [comment]
Thanks for the bug report. I've released a new version (v0.2.24-alpha) on the releases page which should fix this issue. Feel free to open a new issue or make a comment if you notice any other issues.

Thanks.

**Comment by d2dyno** [comment]
Still getting empty scraping. This is what the output panel says, when I put a manual link or let it search automatically:

Setting new movie: Movie [title=Title [title="" source="Data18 Web Content"], originalTitle=OriginalTitle [originalTitle="" source="Data18 Web Content"], sortTitle=SortTitle [sortTitle="" source="Data18 Web Content"], set=Set [set="" source="Data18 Web Content"], rating=Rating [maxRating="0.0", rating=""  source="Data18 Web Content"], year=Year [year="" source="Data18 Web Content"], top250=Top250 [top250="" source="Data18 Web Content"], trailer = Trailer [trailer="" source="Data18 Web Content"], votes=Votes [votes="" source="Data18 Web Content"], outline=Outline [outline="" source="Data18 Web Content"], plot=Plot [plot="" source="Data18 Web Content"], tagline=Tagline [tagline="" source="Data18 Web Content"], studio=Studio [studio="" source="Data18 Web Content"]releaseDate=ReleaseDate [releasedate="" source="Data18 Web Content"], runtime=Runtime [runtime="" source="Data18 Web Content"], posters=[], fanart=[], extrafanart = [], mpaa=MPAARating [MPAARating="XXX" source="Data18 Web Content"], id=ID [id="1122758" source="Data18 Web Content"], genres=[], tags=[], actors=[], directors=[]]

**Comment by d2dyno** [comment]
I'm guessing my previous post was due to an issue on their end because the same procedure as before now works.

**Comment by Darklyter** [comment]
Still have the problem here, using v0.2.24-alpha:

Movie scraped = Movie [title=Title [title="" source="Data18 Web Content"], originalTitle=OriginalTitle [originalTitle="" source="Data18 Web Content"], sortTitle=SortTitle [sortTitle="" source="Data18 Web Content"], set=Set [set="" source="Data18 Web Content"], rating=Rating [maxRating="0.0", rating=""  source="Data18 Web Content"], year=Year [year="" source="Data18 Web Content"], top250=Top250 [top250="" source="Data18 Web Content"], trailer = Trailer [trailer="" source="Data18 Web Content"], votes=Votes [votes="" source="Data18 Web Content"], outline=Outline [outline="" source="Data18 Web Content"], plot=Plot [plot="" source="Data18 Web Content"], tagline=Tagline [tagline="" source="Data18 Web Content"], studio=Studio [studio="" source="Data18 Web Content"]releaseDate=ReleaseDate [releasedate="" source="Data18 Web Content"], runtime=Runtime [runtime="" source="Data18 Web Content"], posters=[], fanart=[], extrafanart = [], mpaa=MPAARating [MPAARating="XXX" source="Data18 Web Content"], id=ID [id="1164961" source="Data18 Web Content"], genres=[], tags=[], actors=[], directors=[]]
Scraping complete of siteScraper = Data18 Web Content
Read in amalgamation preferences from AmalgamationSettings.json
Skipping amalgamation process as there is only one movie
Setting new movie: Movie [title=Title [title="" source="Data18 Web Content"], originalTitle=OriginalTitle [originalTitle="" source="Data18 Web Content"], sortTitle=SortTitle [sortTitle="" source="Data18 Web Content"], set=Set [set="" source="Data18 Web Content"], rating=Rating [maxRating="0.0", rating=""  source="Data18 Web Content"], year=Year [year="" source="Data18 Web Content"], top250=Top250 [top250="" source="Data18 Web Content"], trailer = Trailer [trailer="" source="Data18 Web Content"], votes=Votes [votes="" source="Data18 Web Content"], outline=Outline [outline="" source="Data18 Web Content"], plot=Plot [plot="" source="Data18 Web Content"], tagline=Tagline [tagline="" source="Data18 Web Content"], studio=Studio [studio="" source="Data18 Web Content"]releaseDate=ReleaseDate [releasedate="" source="Data18 Web Content"], runtime=Runtime [runtime="" source="Data18 Web Content"], posters=[], fanart=[], extrafanart = [], mpaa=MPAARating [MPAARating="XXX" source="Data18 Web Content"], id=ID [id="1164961" source="Data18 Web Content"], genres=[], tags=[], actors=[], directors=[]]

**Comment by d2dyno** [comment]
Can confirm, still scattered issues. Almost never pulls artwork even if it manages to get metadata. @DoctorD1501
